#include <array>
#include <span>
#include <string_view>

#include "contracts/assets.h"

// GENERATED by scripts/generate_symphony_assets.py from
// lib/src/cli/assets/symphonies/*.yaml -- the shipped symphony starters
// (27q). The shipped files and these literals are byte-identical, and
// tests/data/contracts/symphony_spec_test.cpp fails the build the moment
// they drift. Edit the FILES, then regenerate; never edit a literal here.

namespace apogee::harness {
// clang-format off
namespace {

constexpr std::array<BundledSymphony, 3> kSymphonies{{
    {.name = "describe-answer", .text = R"SYMPHONY(# A shipped symphony (27q): an image described by the suite's vision member,
# then a question about it answered from that description by its chat
# member -- so a chat model that cannot see still answers about a picture.
# What it shows: a stage that takes the input's image (image: true).
#
#   apogee symphonies play describe-answer --image photo.jpg --input "How many people are in it?"
#   apogee symphonies create my-look --from describe-answer
name: describe-answer
description: Describe an image with the vision member, then answer a question about it from the description.
input:
  description: A question about the image, which is given with --image.
  image: true
stages:
  - name: describe
    role: vision
    image: true
    answer_tokens: 500
    prompt: |
      Describe this image in detail: the objects and the people in it, any text it shows word for word, the colours, the counts and the layout. Pay particular attention to anything that bears on this question: {{input}}
  - name: answer
    role: chat
    answer_tokens: 300
    prompt: |
      Below is a description of an image, and a question about the image.

      Description:
      {{describe}}

      Question: {{input}}

      Answer the question from the description alone. If the description does not say, reply that the description of the image does not say.
)SYMPHONY"},
    {.name = "extract-facts", .text = R"SYMPHONY(# A shipped symphony (27q): one stage on the suite's extraction member, its
# answer held to a JSON Schema -- on a local member by a grammar (26f), so it
# is valid JSON by construction, never coaxed out of the prompt.
#
#   apogee symphonies play extract-facts --input "$(cat article.txt)"
#   apogee symphonies create my-extract --from extract-facts
name: extract-facts
description: Pull the key facts out of a text as one JSON document, held to its schema.
input:
  description: The text to read.
stages:
  - name: extract
    role: extraction
    answer_tokens: 800
    prompt: |
      Read the text below and record its key facts: what it is about, the people and the places it names, the dates it gives, and each fact it states, one per entry. Leave a list empty when the text names none.

      Text:
      {{input}}
    schema: |
      {
        "type": "object",
        "properties": {
          "topic": {"type": "string"},
          "people": {"type": "array", "items": {"type": "string"}},
          "places": {"type": "array", "items": {"type": "string"}},
          "dates": {"type": "array", "items": {"type": "string"}},
          "facts": {"type": "array", "items": {"type": "string"}}
        },
        "required": ["topic", "people", "places", "dates", "facts"],
        "additionalProperties": false
      }
)SYMPHONY"},
    {.name = "summarize-verify", .text = R"SYMPHONY(# A shipped symphony (27q): a passage summarized by the suite's utility
# member, then checked against the passage and corrected by its chat member.
# What it shows: output threading -- stage two reads stage one's answer as
# {{summarize}}, beside the input as {{input}}.
#
#   apogee symphonies play summarize-verify --input "$(cat notes.txt)"
#   apogee symphonies create my-summary --from summarize-verify
name: summarize-verify
description: Summarize a passage, then check the summary against the passage and correct it.
input:
  description: The passage to summarize.
stages:
  - name: summarize
    role: utility
    answer_tokens: 400
    prompt: |
      Summarize the passage below in at most three sentences. Keep every name, number and date exactly as the passage gives it.

      Passage:
      {{input}}
  - name: verify
    role: chat
    answer_tokens: 400
    prompt: |
      Here is a passage and a summary of it.

      Passage:
      {{input}}

      Summary:
      {{summarize}}

      Check the summary against the passage. Correct anything it gets wrong and add any key fact it leaves out, in at most three sentences. Reply with the final summary only.
)SYMPHONY"},
}};

}  // namespace

// clang-format on

std::span<const BundledSymphony> bundled_symphonies() noexcept {
    return kSymphonies;
}

}  // namespace apogee::harness
