#include <array>
#include <span>
#include <string>
#include <string_view>

#include "contracts/assets.h"

// GENERATED by scripts/generate_training_assets.py from
// lib/src/cli/assets/mlx/*.py -- the mlx backend's driver. The shipped file
// and this literal are byte-identical, and tests/data/contracts/assets_test.cpp
// fails the build the moment they drift. Edit the FILE, then regenerate; never
// edit a literal here.

namespace apogee::harness {
// clang-format off
namespace {

/// The chunks of one file, joined once. A file is stored as several raw
/// string literals (see the generator's docstring) and read as one text.
[[nodiscard]] std::string join(std::span<const std::string_view> chunks) {
    std::string out;
    for (const std::string_view chunk : chunks) {
        out.append(chunk);
    }
    return out;
}

constexpr std::array<std::string_view, 1> kMlxMlxConvertPy{{
    R"PY(#!/usr/bin/env python3
"""MLX conversion driver for `apogee models convert --mlx` (Apple silicon).

Makes ONE full-weight SafeTensors snapshot (a Hugging Face layout --
config.json, the tokenizer files, the shards) into an MLX model directory with
`mlx_lm`'s own `convert`, quantized or at a floating-point type, and exits. It
never downloads, never reads Apogee's config, and never touches the model
store: Apogee names a local snapshot and a staging path, verifies what lands
there, and commits it by the store's own rule.

Runs under the Python environment Apogee owns, never the system Python.
Requires `mlx-lm` there:  apogee train setup --with mlx

    mlx_convert.py --hf-path <snapshot> --mlx-path <out>
                   [--q-bits N [--q-group-size N] [--q-mode M] | --dtype T]

`--q-bits` quantizes (mlx-lm's own scheme: N bits a weight in groups, a scale
and bias each); without it the weights are written at `--dtype` (`bfloat16`,
`float16`, `float32`). `<out>` must not exist: mlx-lm refuses to write into a
path that does, and so does this.

The training drivers' protocol, one JSON object per line on stdout:
  {"message": "..."}                       as it goes
  {"error": "..."}                         fatal; a non-zero exit follows
  {"converted": "<out>", "quantized": B, "mlx_lm": "..."}   at the end

Everything a library prints goes to stderr, which Apogee captures: the
protocol's stdout is a duplicate of the original descriptor, and descriptor 1
itself is pointed at stderr before anything is imported.
"""

import argparse
import json
import os
import signal
import sys

# ── Protective environment, before any ML import ─────────────────────────────
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
# The snapshot is a local directory. These make anything else fail loudly
# rather than download quietly -- the converter's model card included.
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"

# Ctrl-C at a terminal reaches the whole foreground process group. Apogee
# ends this child itself and removes what it wrote; a KeyboardInterrupt here
# would race it with a traceback.
signal.signal(signal.SIGINT, signal.SIG_IGN)

_OUT = os.fdopen(os.dup(1), "w", encoding="utf-8", newline="\n")
os.dup2(2, 1)
sys.stdout = sys.stderr


def emit(obj):
    _OUT.write(json.dumps(obj) + "\n")
    _OUT.flush()


def fail(message, code=1):
    emit({"error": message})
    return code


def arguments(argv):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--hf-path", required=True)
    parser.add_argument("--mlx-path", required=True)
    parser.add_argument("--q-bits", type=int, default=0)
    parser.add_argument("--q-group-size", type=int, default=0)
    parser.add_argument("--q-mode", default="")
    parser.add_argument("--dtype", default="")
    return parser.parse_args(argv)


def main(argv):
    args = arguments(argv)
    if not os.path.isdir(args.hf_path):
        return fail(f"{args.hf_path} is not a local snapshot directory", 2)
    if os.path.exists(args.mlx_path):
        return fail(f"{args.mlx_path} already exists -- a conversion never writes over one", 2)

    emit({"message": "loading mlx-lm"})
    try:
        import mlx_lm
        from mlx_lm.convert import convert
    except ImportError as exc:
        return fail(
            f"mlx-lm is not installed in Apogee's Python environment ({exc}) -- "
            "apogee train setup --with mlx",
            3,
        )

    options = {"hf_path": args.hf_path, "mlx_path": args.mlx_path}
    if args.q_bits > 0:
        options["quantize"] = True
        options["q_bits"] = args.q_bits
        if args.q_group_size > 0:
            options["q_group_size"] = args.q_group_size
        if args.q_mode and args.q_mode != "affine":
            # Only an older mlx-lm lacks the keyword; affine is its default.
            options["q_mode"] = args.q_mode
    elif args.dtype:
        options["dtype"] = args.dtype

    emit({"message": "quantizing" if args.q_bits > 0 else "converting"})
    try:
        convert(**options)
    except TypeError as exc:
        if "q_mode" in str(exc) or "dtype" in str(exc):
            version = getattr(mlx_lm, "__version__", "unknown")
            return fail(f"this mlx-lm ({version}) cannot write that precision: {exc}")
        return fail(f"TypeError: {exc}")
    except Exception as exc:  # the converter's own words, whatever they are
        return fail(f"{type(exc).__name__}: {exc}")

    emit(
        {
            "converted": args.mlx_path,
            "quantized": args.q_bits > 0,
            "mlx_lm": getattr(mlx_lm, "__version__", ""),
        }
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
)PY",
}};

const std::string& mlx_mlx_convert_py() {
    static const std::string text = join(kMlxMlxConvertPy);
    return text;
}

constexpr std::array<std::string_view, 3> kMlxMlxGeneratePy{{
    R"PY(#!/usr/bin/env python3
"""MLX inference driver for Apogee's `mlx` backend (Apple silicon).

One process per chat session. It loads ONE model directory (a Hugging Face
layout -- config.json, the tokenizer files, SafeTensors weights) through
`mlx_lm`, holds the model and its attention cache in memory across turns, and
answers requests until its stdin closes, then exits. It never listens on a
port, never reads Apogee's config, and never touches the model store: the
backend tells it everything it needs, one request at a time.

Runs under the Python environment Apogee owns, never the system Python.
Requires `mlx-lm` there:  apogee train setup --with mlx

    mlx_generate.py --model <model directory> [--vision]

`--vision` loads the model through `mlx-vlm` instead, so a request may carry
images (27c): a vision model's own processor reads them, and the reply is
read exactly as a text model's is -- the format's markers and call parser
are `mlx_lm`'s, from the same model directory. A vision model answers every
turn whole, with no cache kept between turns. Requires `mlx-vlm` too:
  apogee train setup --with mlx-vlm

The protocol, one JSON object per line.

In, on stdin:
  {"type": "generate", "id": N, "messages": [...], "tools": [...],
   "sampling": {"temperature": F, "top_p": F, "top_k": N, "min_p": F,
                "repetition_penalty": F, "presence_penalty": F, "seed": N|null},
   "max_tokens": N, "stop": ["..."], "thinking": true|false,
   "session": true|false}
      `messages` and `tools` are the chat-template shapes Hugging Face
      tokenizers take. `session: false` is a side request: it is answered on
      a cache of its own and leaves the conversation's untouched. Under
      `--vision` a message's content may be a list of parts --
      {"type": "text", "text": "..."} and {"type": "image", "image":
      "data:image/png;base64,..."} -- an image always a data: URI, never
      fetched from anywhere.
  {"type": "cancel", "id": N}
      Ends request N's generation; its `done` says "cancelled".
  Closing stdin ends the driver: a generation in flight stops (its `done`
  says "cancelled"), nothing queued behind it starts, and it exits 0.

Out, on stdout:
  {"type": "ready", "protocol": 1, "model_type": "...", "chat_template": B,
   "tool_parser": "..."|null, "thinking": B, "mlx_lm": "...",
   "vision": B, "mlx_vlm": "..."|null}
      Once, after the model loads. `tool_parser` names mlx_lm's parser for
      the model's call format, or null when it has none. `vision` says the
      model was loaded through mlx-vlm and reads images.
  {"type": "text", "id": N, "text": "..."}        answer text, as generated
  {"type": "reasoning", "id": N, "text": "..."}   the model's reasoning
  {"type": "tool_call", "id": N, "name": "...", "arguments": {...}}
  {"type": "done", "id": N, "finish": "stop"|"length"|"tool_calls"|"cancelled",
   "prompt_tokens": N, "cached_tokens": N, "completion_tokens": N}
  {"type": "error", "id": N|null, "kind": "missing_dependency"|"load"|
   "request"|"protocol", "message": "..."}
      A missing dependency or a failed load is fatal: the driver exits
      non-zero after saying so. A bad request is not.

Reasoning and tool calls are read in the model's OWN format: the markers the
tokenizer declares (`mlx_lm` knows each family's), parsed by `mlx_lm`'s own
parser for that format. A family `mlx_lm` has no parser for streams as text,
and the backend's per-family filters read it -- with one exception, the reply
that IS a JSON call (Llama 3's documented tool format), read here because
only here are the offered tools known.

Everything a library prints goes to stderr, which Apogee captures: the
protocol's stdout is a duplicate of the original descriptor, and descriptor 1
itself is pointed at stderr before anything is imported.
"""

import base64
import binascii
import copy
import inspect
import json
import os
import select
import shutil
import signal
import sys
import tempfile
from pathlib import Path

# ── Protective environment, before any ML import ─────────────────────────────
# KMP_DUPLICATE_LIB_OK: two bundled libomp copies in one process abort without it.
# TOKENIZERS_PARALLELISM: forked tokenizer workers deadlock on macOS.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
# The model is a local directory. These make anything else fail loudly rather
# than download quietly.
os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"
os.environ["HF_HUB_DISABLE_TELEMETRY"] = "1"

PROTOCOL = 1

# Ctrl-C at a terminal reaches the whole foreground process group, this child
# with it. The backend cancels a turn over the protocol and keeps the model
# loaded; a driver killed by the same keystroke would cost a reload.
signal.signal(signal.SIGINT, signal.SIG_IGN)

# The protocol channel, then every stray write to descriptor 1 sent to stderr:
# a library's print() must never land between two protocol lines.
_OUT = os.fdopen(os.dup(1), "w", encoding="utf-8", newline="\n")
os.dup2(2, 1)
sys.stdout = sys.stderr


def emit(obj):
    _OUT.write(json.dumps(obj) + "\n")
    _OUT.flush()


def error(kind, message, rid=None):
    emit({"type": "error", "id": rid, "kind": kind, "message": message})


class Input:
    """Lines from stdin, read from the descriptor itself so a poll between
    two tokens sees exactly what has arrived (a buffered reader would hide a
    cancel inside its buffer)."""

    def __init__(self):
        self.fd = sys.stdin.fileno()
        self.buffer = b""
        self.eof = False
        self.queued = []

    def _fill(self, timeout):
        if self.eof:
            return False
        ready, _, _ = select.select([self.fd], [], [], timeout)
        if not ready:
            return False
        chunk = os.read(self.fd, 65536)
        if not chunk:
            self.eof = True
            return False
        self.buffer += chunk
        return True

    def _take(self):
        lines = []
        while b"\n" in self.buffer:
            line, self.buffer = self.buffer.split(b"\n", 1)
            lines.append(line.decode("utf-8", "replace"))
        return lines

    def next_line(self):
        """The next line, blocking; None once stdin has closed."""
        while True:
            if self.queued:
                return self.queued.pop(0)
            lines = self._take()
            if lines:
                self.queued.extend(lines)
                continue
            if self.eof:
                if self.buffer:
                    rest, self.buffer = self.buffer, b""
                    return rest.decode("utf-8", "replace")
                return None
            self._fill(None)

    def poll(self):
        """Lines that have arrived, without waiting."""
        while self._fill(0):
            pass
        lines = self._take()
        return lines


def parse_json_line(line):
    line = line.strip()
    if not line:
        return None
    try:
        value = json.loads(line)
    except ValueError:
        return {"type": "_invalid", "text": line}
    return value if isinstance(value, dict) else {"type": "_invalid", "text": line}


# ── Reading a reply ──────────────────────────────────────────────────────────

PYTHON_TAG = "<|python_tag|>"


def json_calls(text, tool_names):
    """Llama 3's tool format: the reply IS the call, as
    {"name": ..., "parameters": {...}} (or "arguments"), optionally after
    <|python_tag|>. One call: the format holds one per message, and Llama's
    own template refuses to render a second back ("only supports single
    tool-calls at once"), so -- as llama.cpp's reader does -- the first object
    is the call and whatever follows it is dropped. An object that does not
    name an offered tool with an arguments object is not a call at all."""
    text = text.strip()
    if text.startswith(PYTHON_TAG):
        text = text[len(PYTHON_TAG):].strip()
    try:
        value, _ = json.JSONDecoder().raw_decode(text)
    except ValueError:
        return None
    if isinstance(value, list):
        value = value[0] if value else None
    if not isinstance(value, dict):
        return None
    if isinstance(value.get("function"), dict):
        value = value["function"]
    name = value.get("name")
    arguments = value.get("parameters", value.get("arguments"))
    if isinstance(arguments, str):
        try:
            arguments = json.loads(arguments)
        except ValueError:
            return None
    if not isinstance(name, str) or name not in tool_names or not isinstance(arguments, dict):
        return None
    return [{"name": name, "arguments": arguments}]


class Reader:
    """Splits generated text into answer, reasoning and tool calls by the
    markers the model's format declares, holding back any tail that could
    still become a marker. Stop strings end the reply."""

    def __init__(self, rid, think, tool, parser, tools, json_tools, stops, reasoning):
        self.rid = rid
        self.think = think          # (start, end) or None
        self.tool = tool            # (start, end) or None; end may be None
        self.parser = parser
        self.tools = tools
        self.tool_names = {t.get("function", {}).get("name") for t in tools or []}
        self.stops = [s for s in stops if s]
        self.state = "reasoning" if reasoning else "normal"
        self.pending = ""
        self.tool_text = ""
        self.calls = []
        self.stopped = False
        # Llama 3's JSON reply: decided on the reply's first visible text.
        self.lead = bool(json_tools) and not reasoning
        self.lead_text = ""
        self.holding_json = False

    def _out(self, kind, text):
        if text:
            emit({"type": kind, "id": self.rid, "text": text})

    def _markers(self):
        markers = []
        if self.state == "normal":
            if self.think:
                markers.append((self.think[0], "reasoning"))
            if self.tool:
                markers.append((self.tool[0], "tool"))
        elif self.state == "reasoning":
            if self.think:
                markers.append((self.think[1], "normal"))
            if self.tool:
                markers.append((self.tool[0], "tool"))
        elif self.state == "tool":
            if self.tool and self.tool[1]:
                markers.append((self.tool[1], "normal"))
            return markers
        for stop in self.stops:
            markers.append((stop, None))
        return markers

    def _finish_tool(self, closed):
        text = self.tool_text
        self.tool_text = ""
        parsed = None
        if self.parser is not None:
            try:
                parsed = self.parser(text, self.tools)
            except Exception:  # noqa: BLE001 -- any parser failure is "not a call"
                parsed = None
        items = parsed if isinstance(parsed, list) else ([parsed] if parsed else [])
        calls = []
        for item in items:
            if isinstance(item, dict) and isinstance(item.get("name"), str):
                arguments = item.get("arguments", {})
                if isinstance(arguments, str):
                    try:
                        arguments = json.loads(arguments)
                    except ValueError:
                        arguments = None
                if isinstance(arguments, dict):
                    calls.append({"name": item["name"], "arguments": arguments})
                    continue
            calls = None
            break
        if calls:
            for call in calls:
                self.calls.append(call)
                emit({"type": "tool_call", "id": self.rid, "name": call["name"],
                      "arguments": call["arguments"]})
            return
        # The safety net: a span that opened like a call and is not one goes
        # back out as text, never silently dropped.
        raw = self.tool[0] + text + (self.tool[1] if closed and self.tool[1] else "")
        self._out("text", raw)

    def _route(self, text):
        if not text:
            return
        if self.state == "normal":
            self._out("text", text)
        elif self.state == "reasoning":
            self._out("reasoning", text)
        else:
            self.tool_text += text

    def feed(self, piece):
        """Consumes generated text; True once a stop string ended the reply."""
        if self.stopped or not piece:
            return self.stopped
        if self.holding_json:
            self.lead_text += piece
            return False
        if self.lead:
            self.lead_text += piece
            stripped = self.lead_text.lstrip()
            if not stripped or PYTHON_TAG.startswith(stripped):
                return False
            if stripped.startswith(PYTHON_TAG):
                stripped = stripped[len(PYTHON_TAG):].lstrip()
                if not stripped:
                    return False
            self.lead = False
            if stripped.startswith("{") or stripped.startswith("["):
                self.holding_json = True
                return False
            piece, self.lead_text = self.lead_text, ""
        self.pending += piece
        while True:
            markers = self._markers()
            best = None
            for marker, target in markers:
                at = self.pending.find(marker)
                if at >= 0 and (best is None or at < best[0]):
                    best = (at, marker, target)
            if best is None:
                break
            at, marker, target = best
            self._route(self.pending[:at])
            self.pending = self.pending[at + len(marker):]
            if target is None:
                self.stopped = True
                self.pending = ""
                return True
            if self.state == "tool" and target == "normal":
                self.state = "normal"
                self._finish_tool(closed=True)
            else:
                self.state = target
        # Hold the longest tail that could still begin a marker.
        hold = 0
        for marker, _ in self._markers():
            for size in range(min(len(marker) - 1, len(self.pending)), 0, -1):
                if self.pending.endswith(marker[:size]):
                    hold = max(hold, size)
                    break
        if hold:
            self._route(self.pending[:-hold])
            self.pending = self.pending[-hold:]
        else:
            self._route(self.pending)
            self.pending = ""
        return False

    def finish(self):
        """Ends the reply: what was held is resolved."""
        if self.holding_json or self.lead:
            text, self.lead_text = self.lead_text, ""
            self.holding_json = False
            self.lead = False
)PY",
    R"PY(            calls = json_calls(text, self.tool_names) if text.strip() else None
            if calls:
                for call in calls:
                    self.calls.append(call)
                    emit({"type": "tool_call", "id": self.rid, "name": call["name"],
                          "arguments": call["arguments"]})
                return
            self.feed(text)
        if self.state == "tool":
            self.tool_text += self.pending
            self.pending = ""
            self._finish_tool(closed=False)
            return
        self._route(self.pending)
        self.pending = ""


# ── The model ────────────────────────────────────────────────────────────────


class Driver:
    # Loaded through mlx-vlm, reading images: VisionDriver's.
    vision = False

    def __init__(self, mx, model, tokenizer, api, model_type):
        self.mx = mx
        self.model = model
        self.tokenizer = tokenizer
        self.api = api
        self.model_type = model_type
        self.cache = None
        self.cached = []
        # The cache as it stood where the last prompt's history ended (before
        # its generation prompt), kept only when the cache cannot be cut back
        # -- a sliding window past its size, a recurrent state: the next
        # prompt almost always extends that history, and this is what lets it
        # read only what is new.
        self.checkpoint = None
        self.input = Input()

    def ready(self, version, vlm_version=None):
        tokenizer = self.tokenizer
        tool_parser = None
        if getattr(tokenizer, "has_tool_calling", False):
            parser = getattr(tokenizer, "tool_parser", None)
            module = getattr(parser, "__module__", "") or ""
            tool_parser = module.rsplit(".", 1)[-1] or "unnamed"
        emit({
            "type": "ready",
            "protocol": PROTOCOL,
            "model_type": self.model_type,
            "chat_template": self.has_template(),
            "tool_parser": tool_parser,
            "thinking": bool(getattr(tokenizer, "has_thinking", False)),
            "mlx_lm": version,
            "vision": self.vision,
            "mlx_vlm": vlm_version,
        })

    def has_template(self):
        return bool(getattr(self.tokenizer, "has_chat_template", False))

    def encode(self, text):
        bos = getattr(self.tokenizer, "bos_token", None)
        add_special = bos is None or not text.startswith(bos)
        return list(self.tokenizer.encode(text, add_special_tokens=add_special))

    def render(self, request):
        """The prompt's text and tokens, and where its history ends: the
        boundary before the generation prompt, which a template may write
        differently once the turn it opens is in the history (Gemma 4 opens a
        thinking channel there and drops it after) -- so a checkpoint is
        taken there, the last point the next prompt is sure to share."""
        messages = request.get("messages") or []
        tools = request.get("tools") or None
        tokenizer = self.tokenizer
        if self.has_template():
            kwargs = {"add_generation_prompt": True, "tokenize": False}
            if tools:
                kwargs["tools"] = tools
            if "thinking" in request and request["thinking"] is not None:
                kwargs["enable_thinking"] = bool(request["thinking"])
            text = tokenizer.apply_chat_template(messages, **kwargs)
            prompt = self.encode(text)
            boundary = len(prompt) - 1
            try:
                kwargs["add_generation_prompt"] = False
                history = self.encode(tokenizer.apply_chat_template(messages, **kwargs))
                if 0 < len(history) < len(prompt) and prompt[:len(history)] == history:
                    boundary = len(history)
            except Exception:  # noqa: BLE001 -- no boundary is the cautious answer
                pass
            return text, prompt, boundary
        else:
            # A base model: no format of its own, so a plain transcript it can
            # continue, ended where it starts writing the next user turn.
            lines = []
            for message in messages:
                role = message.get("role", "user")
                label = {"system": "System", "assistant": "Assistant"}.get(role, "User")
                lines.append(f"{label}: {message.get('content') or ''}")
            text = "\n\n".join(lines) + "\n\nAssistant:"
        prompt = self.encode(text)
        return text, prompt, len(prompt) - 1

    def prepare(self, prompt, session):
        """The cache to generate on and the prompt tokens it still needs."""
        make, can_trim, trim = self.api["cache"]
        if not session:
            return make(self.model), prompt, 0
        if self.cache is None:
            self.cache = make(self.model)
            self.cached = []
        shared = 0
        limit = min(len(self.cached), len(prompt))
        while shared < limit and self.cached[shared] == prompt[shared]:
            shared += 1
        # At least one token is always fed: the next token's logits come from it.
        shared = min(shared, len(prompt) - 1)
        excess = len(self.cached) - shared
        if excess > 0:
            trimmed = trim(self.cache, excess) if can_trim(self.cache) else 0
            if trimmed != excess:
                self.cache, shared = self.restore(prompt)
        self.cached = prompt[:shared]
        return self.cache, prompt[shared:], shared

    def restore(self, prompt):
        """A cache that cannot be cut back: the checkpoint, when this prompt
        extends what it holds, else a fresh one."""
        make = self.api["cache"][0]
        if self.checkpoint is not None:
            tokens, saved = self.checkpoint
            if len(tokens) < len(prompt) and prompt[:len(tokens)] == tokens:
                return copy.deepcopy(saved), len(tokens)
        self.checkpoint = None
        return make(self.model), 0

    def feed(self, cache, tokens):
        """Reads `tokens` into `cache`, in chunks, as mlx_lm's own step does."""
        for start in range(0, len(tokens), 2048):
            self.model(self.mx.array(tokens[start:start + 2048])[None], cache=cache)
            self.mx.eval([c.state for c in cache])

    def prefill(self, cache, prompt, shared, boundary):
        """Reads the prompt from `shared` to its last token -- the step reads
        that one, so its logits are the first sample's -- checkpointing the
        cache at `boundary` when it can no longer be cut back there. Returns
        the tokens left for the step."""
        can_trim = self.api["cache"][1]
        end = len(prompt) - 1
        cut = boundary if shared < boundary <= end else end
        self.feed(cache, prompt[shared:cut])
        if cut > shared and not can_trim(cache):
            self.checkpoint = (prompt[:cut], copy.deepcopy(cache))
        self.feed(cache, prompt[cut:end])
        return prompt[end:]

    def cancelled(self, rid):
        for line in self.input.poll():
            message = parse_json_line(line)
            if message is None:
                continue
            if message.get("type") == "cancel" and message.get("id") in (None, rid):
                return True
            if message.get("type") != "cancel":
                self.input.queued.append(line)
        return self.input.eof

    def sampler(self, request):
        """mlx_lm's sampler and logits processors for the values the request
        carries -- the ladder Apogee resolved, nothing guessed here -- with
        its seed set."""
        sampling = request.get("sampling") or {}
        make_sampler, make_logits_processors = self.api["sampling"]
        sampler = make_sampler(
            temp=float(sampling.get("temperature", 0.0) or 0.0),
            top_p=float(sampling.get("top_p", 1.0) if sampling.get("top_p") is not None else 1.0),
            min_p=float(sampling.get("min_p", 0.0) or 0.0),
            top_k=int(sampling.get("top_k", 0) or 0),
        )
        repetition = sampling.get("repetition_penalty")
        presence = sampling.get("presence_penalty")
        processors = make_logits_processors(
            repetition_penalty=repetition if repetition not in (None, 1.0, 1) else None,
            presence_penalty=presence if presence not in (None, 0.0, 0) else None,
        )
        if sampling.get("seed") is not None:
            self.mx.random.seed(int(sampling["seed"]))
        return sampler, processors

    def reader(self, request, text, rid):
        """The reply's reader for a prompt rendered as `text`: the format's
        reasoning markers, its call markers and parser when tools are
        offered, the stop strings."""
        tokenizer = self.tokenizer
        tools = request.get("tools") or []
        think = None
        if getattr(tokenizer, "has_thinking", False):
            think = (tokenizer.think_start, tokenizer.think_end)
        tool = None
        parser = None
        if tools and getattr(tokenizer, "has_tool_calling", False):
            tool = (tokenizer.tool_call_start, tokenizer.tool_call_end)
            parser = tokenizer.tool_parser
        reasoning = False
        if think is not None:
            opened = text.rfind(think[0])
            reasoning = opened >= 0 and opened > text.rfind(think[1])
        stops = list(request.get("stop") or [])
        if not self.has_template():
            stops.append("\nUser:")
        return Reader(rid, think, tool, parser, tools,
                      bool(tools) and tool is None and self.has_template(),
                      stops, reasoning)

    def generate(self, request):
        rid = request.get("id")
        session = request.get("session", True) is not False
        tokenizer = self.tokenizer
        text, prompt, boundary = self.render(request)
        if not prompt:
            error("request", "the rendered prompt is empty", rid)
            return
        cache, suffix, shared = self.prepare(prompt, session)
        sampler, processors = self.sampler(request)
        reader = self.reader(request, text, rid)

        eos = set(getattr(tokenizer, "eos_token_ids", None) or [])
        detokenizer = tokenizer.detokenizer
        detokenizer.reset()
        max_tokens = int(request.get("max_tokens") or 2048)
        generated = []
        produced = 0
        finish = "length"
        if session:
            suffix = self.prefill(cache, prompt, shared, boundary)
        steps = self.api["generate_step"](
            self.mx.array(suffix), self.model, max_tokens=max_tokens, sampler=sampler,
            logits_processors=processors, prompt_cache=cache)
        try:
            for token, _ in steps:
                token = int(token)
                # The step fed this token into the cache before handing it over.
                generated.append(token)
                if token in eos:
                    finish = "stop"
                    break
                produced += 1
                detokenizer.add_token(token)
                if reader.feed(detokenizer.last_segment):
                    finish = "stop"
                    break
                if self.cancelled(rid):
                    finish = "cancelled"
                    break
        finally:
            close = getattr(steps, "close", None)
            if close is not None:
                close()
        if finish != "cancelled" and not reader.stopped:
            detokenizer.finalize()
            reader.feed(detokenizer.last_segment)
        reader.finish()
        if session:
            self.cached = prompt + generated
        if reader.calls and finish != "cancelled":
            finish = "tool_calls"
        emit({"type": "done", "id": rid, "finish": finish, "prompt_tokens": len(prompt),
              "cached_tokens": shared, "completion_tokens": produced})

    def serve(self):
        while True:
            line = self.input.next_line()
            # Closed stdin ends the driver: nothing queued behind it starts.
            if line is None or self.input.eof:
                return 0
            request = parse_json_line(line)
            if request is None:
                continue
            kind = request.get("type")
            if kind == "generate":
                try:
                    self.generate(request)
                except Exception as e:  # noqa: BLE001 -- reported, and the driver lives on
                    # The cache may hold half a turn: start the next one clean.
                    self.cache = None
                    self.cached = []
                    self.checkpoint = None
                    error("request", f"{type(e).__name__}: {e}", request.get("id"))
            elif kind == "cancel":
                continue  # nothing running: a cancel that arrived late
            else:
                error("protocol", f"unknown request: {line[:200]}", request.get("id"))


# ── Images (27c) ─────────────────────────────────────────────────────────────

IMAGE_SUFFIXES = {"image/png": ".png", "image/jpeg": ".jpg", "image/jpg": ".jpg",
                  "image/webp": ".webp", "image/gif": ".gif", "image/bmp": ".bmp"}


def image_file(uri, directory, index):
    """A data: URI's bytes, written into `directory` for the processor to
    open. Anything else is refused: an image is never fetched from anywhere."""
    if not isinstance(uri, str) or not uri.startswith("data:"):
        raise ValueError("an image must arrive as a data: URI -- a remote image is never fetched")
    header, sep, payload = uri.partition(",")
    if not sep or not header.endswith(";base64"):
        raise ValueError("an image's data: URI must be base64")
    try:
        data = base64.b64decode(payload, validate=False)
    except (binascii.Error, ValueError) as e:
        raise ValueError(f"an image's data: URI does not decode: {e}") from None
    if not data:
        raise ValueError("an image's data: URI is empty")
    media = header[len("data:"):-len(";base64")].lower()
    path = os.path.join(directory, f"image-{index}{IMAGE_SUFFIXES.get(media, '.img')}")
    with open(path, "wb") as out:
        out.write(data)
    return path


def with_images(messages, directory):
    """The messages with each image part pointing at its file, in the
    content-part shape a vision model's template places images by, and the
    files in prompt order."""
    out = []
    images = []
    for message in messages:
        content = message.get("content")
        if not isinstance(content, list):
            out.append(message)
            continue
        parts = []
        for part in content:
            kind = part.get("type") if isinstance(part, dict) else None
            if kind == "image":
)PY",
    R"PY(                path = image_file(part.get("image"), directory, len(images))
                images.append(path)
                parts.append({"type": "image", "image": path})
            elif kind == "text":
                parts.append({"type": "text", "text": part.get("text") or ""})
            else:
                raise ValueError(f"a content part of type {kind!r} cannot be read here")
        out.append(dict(message, content=parts))
    return out, images


class VisionDriver(Driver):
    """A model loaded through mlx-vlm: its own processor reads the images,
    and mlx_lm's tokenizer over the same directory supplies the format --
    the template, the reasoning markers, the call parser -- so a reply is
    read exactly as a text model's is. Every turn is answered whole: no cache
    is kept between turns."""

    vision = True

    def __init__(self, mx, model, tokenizer, api, model_type, processor):
        super().__init__(mx, model, tokenizer, api, model_type)
        self.processor = processor

    def options(self, request):
        """The sampling, in the form this mlx-vlm takes it: mlx_lm's sampler
        where its step accepts one, its own knobs otherwise."""
        accepted = self.api["vision_parameters"]
        if accepted is None or "sampler" in accepted:
            sampler, processors = self.sampler(request)
            return {"sampler": sampler, "logits_processors": processors}
        sampling = request.get("sampling") or {}
        if sampling.get("seed") is not None:
            self.mx.random.seed(int(sampling["seed"]))
        temperature = float(sampling.get("temperature", 0.0) or 0.0)
        options = {"temp" if "temp" in accepted else "temperature": temperature}
        if sampling.get("top_p") is not None:
            options["top_p"] = float(sampling["top_p"])
        repetition = sampling.get("repetition_penalty")
        if repetition not in (None, 1.0, 1):
            options["repetition_penalty"] = float(repetition)
        return options

    def generate(self, request):
        rid = request.get("id")
        directory = tempfile.mkdtemp(prefix="apogee-mlx-images-")
        try:
            self.generate_in(request, rid, directory)
        finally:
            shutil.rmtree(directory, ignore_errors=True)

    def generate_in(self, request, rid, directory):
        try:
            messages, images = with_images(request.get("messages") or [], directory)
        except ValueError as e:
            error("request", str(e), rid)
            return
        if not self.has_template():
            error("request", "the model ships no chat template to place a turn in", rid)
            return
        rendered = dict(request, messages=messages)
        kwargs = {"add_generation_prompt": True, "tokenize": False}
        if request.get("tools"):
            kwargs["tools"] = request["tools"]
        if request.get("thinking") is not None:
            kwargs["enable_thinking"] = bool(request["thinking"])
        text = self.tokenizer.apply_chat_template(messages, **kwargs)
        reader = self.reader(rendered, text, rid)
        max_tokens = int(request.get("max_tokens") or 2048)
        results = self.api["vision"](self.model, self.processor, text,
                                     image=images or None, max_tokens=max_tokens,
                                     **self.options(request))
        prompt_tokens = 0
        produced = 0
        finish = None
        try:
            for result in results:
                prompt_tokens = int(getattr(result, "prompt_tokens", 0) or prompt_tokens)
                produced = int(getattr(result, "generation_tokens", 0) or produced)
                if reader.feed(getattr(result, "text", "") or ""):
                    finish = "stop"
                    break
                if self.cancelled(rid):
                    finish = "cancelled"
                    break
        finally:
            close = getattr(results, "close", None)
            if close is not None:
                close()
        if finish is None:
            # The step ended it: the model's end of turn, or the cap.
            finish = "length" if produced >= max_tokens else "stop"
        reader.finish()
        if reader.calls and finish != "cancelled":
            finish = "tool_calls"
        emit({"type": "done", "id": rid, "finish": finish, "prompt_tokens": prompt_tokens,
              "cached_tokens": 0, "completion_tokens": produced})


def vision_parameters():
    """What this mlx-vlm's step takes -- where its versions keep it -- or None
    when that cannot be told."""
    for module in ("mlx_vlm.generate", "mlx_vlm.utils"):
        try:
            step = getattr(__import__(module, fromlist=["generate_step"]), "generate_step")
            return set(inspect.signature(step).parameters)
        except (ImportError, AttributeError, TypeError, ValueError):
            continue
    return None


def model_type_of(model_dir):
    try:
        with open(os.path.join(model_dir, "config.json"), encoding="utf-8") as f:
            config = json.load(f)
    except (OSError, ValueError):
        return None
    return config.get("model_type") if isinstance(config, dict) else None


def main(argv):
    model_dir = None
    if len(argv) >= 3 and argv[1] == "--model":
        model_dir = argv[2]
    if not model_dir:
        error("protocol", "usage: mlx_generate.py --model <model directory> [--vision]")
        return 2
    vision = "--vision" in argv[3:]

    try:
        import mlx.core as mx
        import mlx_lm
        from mlx_lm import load
        from mlx_lm.generate import generate_step
        from mlx_lm.models.cache import can_trim_prompt_cache, make_prompt_cache, trim_prompt_cache
        from mlx_lm.sample_utils import make_logits_processors, make_sampler
    except ImportError as e:
        error("missing_dependency",
              f"mlx-lm is not installed in the Python environment ({e}). "
              "Run: apogee train setup --with mlx")
        return 3

    if not os.path.isfile(os.path.join(model_dir, "config.json")):
        error("load", f"{model_dir} is not a model directory: it has no config.json")
        return 4
    model_type = model_type_of(model_dir)
    api = {
        "generate_step": generate_step,
        "sampling": (make_sampler, make_logits_processors),
        "cache": (make_prompt_cache, can_trim_prompt_cache, trim_prompt_cache),
    }
    version = getattr(mlx_lm, "__version__", "unknown")
    if vision:
        return serve_vision(mx, api, model_dir, model_type, version)
    try:
        model, tokenizer = load(model_dir)
    except Exception as e:  # noqa: BLE001 -- the reason is the message
        error("load", f"could not load {model_dir}: {type(e).__name__}: {e}")
        return 4

    driver = Driver(mx, model, tokenizer, api, model_type)
    driver.ready(version)
    return driver.serve()


def serve_vision(mx, api, model_dir, model_type, version):
    """The model through mlx-vlm, so its turns may carry images (27c)."""
    try:
        import mlx_vlm
        from mlx_lm.utils import load_tokenizer
        from mlx_vlm import load as load_vision
        from mlx_vlm import stream_generate
    except ImportError as e:
        error("missing_dependency",
              f"mlx-vlm is not installed in the Python environment ({e}), so this model's "
              "images cannot be read. Run: apogee train setup --with mlx-vlm")
        return 3
    try:
        model, processor = load_vision(model_dir)
        # The format -- template, reasoning markers, call parser -- as mlx_lm
        # reads it from the same directory, so a reply reads as a text one does.
        tokenizer = load_tokenizer(Path(model_dir))
    except Exception as e:  # noqa: BLE001 -- the reason is the message
        error("load", f"could not load {model_dir} through mlx-vlm: {type(e).__name__}: {e}")
        return 4
    api = dict(api, vision=stream_generate, vision_parameters=vision_parameters())
    driver = VisionDriver(mx, model, tokenizer, api, model_type, processor)
    driver.ready(version, vlm_version_of(mlx_vlm))
    return driver.serve()


def vlm_version_of(module):
    version = getattr(module, "__version__", None)
    if version is None:
        try:
            from mlx_vlm.version import __version__ as version
        except ImportError:
            version = "unknown"
    return str(version)


if __name__ == "__main__":
    sys.exit(main(sys.argv))
)PY",
}};

const std::string& mlx_mlx_generate_py() {
    static const std::string text = join(kMlxMlxGeneratePy);
    return text;
}

}  // namespace

std::span<const BundledScript> bundled_mlx_scripts() {
    static const std::array<BundledScript, 2> scripts{{
        {.name = "mlx_convert.py", .text = mlx_mlx_convert_py()},
        {.name = "mlx_generate.py", .text = mlx_mlx_generate_py()},
    }};
    return scripts;
}

// clang-format on

}  // namespace apogee::harness
