#pragma once

#include <string>

/// The page `apogee graph export html` fills (27m): `assets/graph/graph.html`,
/// compiled in like the clerks' prompts -- its CSS and its hand-rolled
/// force layout, search, legend and card inline, no library, no reference to
/// anything outside the file. Generated by `scripts/generate_graph_assets.py`
/// as raw-string chunks; `tests/business/graph/export_test.cpp` holds the
/// literal byte-identical to the file.
///
/// Placeholders, each `{{name}}`: `title` and `cap_note` (HTML text) and
/// `data` (the one embedded JSON block) -- `graph/export_html` fills them in
/// one pass and refuses any other.
namespace apogee::graph {

[[nodiscard]] const std::string& html_template();

}  // namespace apogee::graph
