#!/usr/bin/env python3
"""Regenerate the compiled-in symphony starters (27q).

    python3 scripts/generate_symphony_assets.py        # run from anywhere

Reads every shipped spec file and rewrites the one generated translation unit:

    assets/symphonies/*.yaml  ->  source/data/contracts/assets_symphonies.cpp

The FILES are the source of truth: edit them, run this, and commit both.
tests/data/contracts/symphony_spec_test.cpp fails the build the moment a
literal and its file differ, or a file has no literal -- the contract the
bundled agents and the kits keep. Each starter is one raw string, far under
MSVC's 16 380-byte literal limit; the script refuses one that is not.
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPECS = ROOT / "assets" / "symphonies"
OUT = ROOT / "source" / "data" / "contracts" / "assets_symphonies.cpp"

DELIMITER = "SYMPHONY"
LIMIT = 15_000


def generate() -> str:
    files = sorted(SPECS.glob("*.yaml"))
    if not files:
        raise SystemExit(f"{SPECS}: no starters to compile in")
    out = [
        "#include <array>",
        "#include <span>",
        "#include <string_view>",
        "",
        '#include "contracts/assets.h"',
        "",
        "// GENERATED by scripts/generate_symphony_assets.py from",
        "// lib/src/cli/assets/symphonies/*.yaml -- the shipped symphony starters",
        "// (27q). The shipped files and these literals are byte-identical, and",
        "// tests/data/contracts/symphony_spec_test.cpp fails the build the moment",
        "// they drift. Edit the FILES, then regenerate; never edit a literal here.",
        "",
        "namespace apogee::harness {",
        "// clang-format off",
        "namespace {",
        "",
        f"constexpr std::array<BundledSymphony, {len(files)}> kSymphonies{{{{",
    ]
    for path in files:
        text = path.read_text(encoding="utf-8")
        if f"){DELIMITER}\"" in text:
            raise SystemExit(f"{path}: contains the raw-string terminator ){DELIMITER}\"")
        if len(text.encode("utf-8")) > LIMIT:
            raise SystemExit(f"{path}: over {LIMIT} bytes -- split it or chunk the literal")
        out.append(f'    {{.name = "{path.stem}", .text = R"{DELIMITER}({text}){DELIMITER}"}},')
    out += [
        "}};",
        "",
        "}  // namespace",
        "",
        "// clang-format on",
        "",
        "std::span<const BundledSymphony> bundled_symphonies() noexcept {",
        "    return kSymphonies;",
        "}",
        "",
        "}  // namespace apogee::harness",
        "",
    ]
    return "\n".join(out)


def main() -> None:
    OUT.write_text(generate(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
