#!/usr/bin/env python3
"""Regenerate the compiled-in training assets.

    python3 scripts/generate_training_assets.py        # run from lib/src/cli

Reads the shipped files and rewrites the two generated translation units:

    assets/training/kits/*.yaml                -> source/harness/assets_training.cpp
    assets/training/*.py                       -> source/harness/assets_training.cpp
    third_party/llama.cpp-convert/**           -> source/harness/assets_converter.cpp

The FILES are the source of truth: edit them (or move the converter's pin),
run this, and commit both. tests/harness/assets_test.cpp fails the build
the moment a literal and its file differ.

Every file is emitted as a list of raw-string chunks under 15 000 bytes,
split on line boundaries, and joined at first use. MSVC refuses a single
string literal over 16 380 bytes and a concatenation over 65 535, so one
literal per file would not build on two of the six release targets.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets" / "training"
CONVERTER = ROOT / "third_party" / "llama.cpp-convert"
OUT_TRAINING = ROOT / "source" / "harness" / "assets_training.cpp"
OUT_CONVERTER = ROOT / "source" / "harness" / "assets_converter.cpp"

CHUNK_BYTES = 15_000

# Generated code is never reformatted: the long symbol names and the
# one-line table rows would be reflowed by clang-format, and then a
# regeneration would fail format-check until someone ran the formatter.
JOIN_HELPER = """// clang-format off
namespace {

/// The chunks of one file, joined once. A file is stored as several raw
/// string literals (see the generator's docstring) and read as one text.
[[nodiscard]] std::string join(std::span<const std::string_view> chunks) {
    std::string out;
    for (const std::string_view chunk : chunks) {
        out.append(chunk);
    }
    return out;
}
"""


def chunks_of(text: str) -> list[str]:
    """Splits on line boundaries so every chunk stays under the limit."""
    pieces: list[str] = []
    current = ""
    for line in text.splitlines(keepends=True):
        if len((current + line).encode("utf-8")) > CHUNK_BYTES and current:
            pieces.append(current)
            current = ""
        current += line
    if current or not pieces:
        pieces.append(current)
    return pieces


def literal_array(symbol: str, text: str, delimiter: str) -> str:
    if f"){delimiter}\"" in text:
        raise SystemExit(f"{symbol}: the text contains the raw-string terminator ){delimiter}\"")
    pieces = chunks_of(text)
    lines = [f"constexpr std::array<std::string_view, {len(pieces)}> {symbol}{{{{"]
    for piece in pieces:
        lines.append(f'    R"{delimiter}({piece}){delimiter}",')
    lines.append("}};")
    return "\n".join(lines) + "\n"


def accessor(name: str, symbol: str) -> str:
    return (
        f"const std::string& {name}() {{\n"
        f"    static const std::string text = join({symbol});\n"
        f"    return text;\n"
        f"}}\n"
    )


def identifier(path: str) -> str:
    """A snake_case identifier for a path: runs of non-alphanumerics become
    one underscore, so `conversion/__init__.py` is `conversion_init_py`
    (a double underscore anywhere is a reserved identifier in C++)."""
    words = [w.lower() for w in re.split(r"[^0-9A-Za-z]+", path) if w]
    return "_".join(words)


def constant(path: str) -> str:
    """The `kCamelCase` spelling the project's naming rule wants for a
    global constant."""
    return "k" + "".join(w[:1].upper() + w[1:] for w in identifier(path).split("_"))


def generate_training() -> str:
    kits = sorted(ASSETS.glob("kits/*.yaml"))
    scripts = sorted(ASSETS.glob("*.py"))
    if not kits or not scripts:
        raise SystemExit("no kits or scripts found under assets/training")
    out = [
        "#include <array>",
        "#include <span>",
        "#include <string>",
        "#include <string_view>",
        "",
        '#include "harness/assets.h"',
        "",
        "// GENERATED by scripts/generate_training_assets.py from",
        "// lib/src/cli/assets/training/kits/*.yaml and assets/training/*.py. The",
        "// shipped files and these literals are byte-identical, and",
        "// tests/harness/assets_test.cpp fails the build the moment they drift -- the",
        "// same contract the config template and the bundled agents keep. Edit the",
        "// FILES, then regenerate; never edit a literal here.",
        "",
        "namespace apogee::harness {",
        JOIN_HELPER,
    ]
    kit_names = []
    for kit in kits:
        name = kit.stem
        symbol = constant("kit_" + name)
        out.append(literal_array(symbol, kit.read_text(encoding="utf-8"), "KIT"))
        out.append(accessor("kit_" + identifier(name), symbol))
        kit_names.append(name)
    script_names = []
    for script in scripts:
        name = script.name
        symbol = constant("script_" + name)
        out.append(literal_array(symbol, script.read_text(encoding="utf-8"), "PY"))
        out.append(accessor("script_" + identifier(name), symbol))
        script_names.append(name)
    out.append("}  // namespace")
    out.append("")
    out.append("std::span<const BundledKit> bundled_kits() {")
    out.append(f"    static const std::array<BundledKit, {len(kit_names)}> kits{{{{")
    for name in kit_names:
        out.append(f'        {{.name = "{name}", .text = kit_{identifier(name)}()}},')
    out.append("    }};")
    out.append("    return kits;")
    out.append("}")
    out.append("")
    out.append("std::span<const BundledScript> bundled_training_scripts() {")
    out.append(f"    static const std::array<BundledScript, {len(script_names)}> scripts{{{{")
    for name in script_names:
        out.append(f'        {{.name = "{name}", .text = script_{identifier(name)}()}},')
    out.append("    }};")
    out.append("    return scripts;")
    out.append("}")
    out.append("")
    out.append("// clang-format on")
    out.append("")
    out.append("}  // namespace apogee::harness")
    return "\n".join(out) + "\n"


def generate_converter() -> str:
    files = sorted(
        p for p in CONVERTER.rglob("*") if p.is_file() and p.suffix in {".py", ".jinja"}
    )
    if not files:
        raise SystemExit("no converter files found under third_party/llama.cpp-convert")
    out = [
        "#include <array>",
        "#include <span>",
        "#include <string>",
        "#include <string_view>",
        "",
        '#include "harness/assets.h"',
        "",
        "// GENERATED by scripts/generate_training_assets.py from",
        "// lib/src/cli/third_party/llama.cpp-convert/** -- llama.cpp's",
        "// `convert_hf_to_gguf.py`, its `conversion/` package and the chat templates",
        "// it consults, vendored at the pinned revision (see that directory's",
        "// README). Never edited: a fix goes upstream and moves the pin. Seeded",
        "// under training/scripts/convert/ by the one seeding path; the doctor's",
        "// `converter` row shows the drift.",
        "",
        "namespace apogee::harness {",
        JOIN_HELPER,
    ]
    names = []
    for path in files:
        relative = path.relative_to(CONVERTER).as_posix()
        symbol = constant("convert_" + relative)
        out.append(literal_array(symbol, path.read_text(encoding="utf-8"), "CONV"))
        out.append(accessor("convert_" + identifier(relative), symbol))
        names.append(relative)
    out.append("}  // namespace")
    out.append("")
    out.append("std::span<const BundledScript> bundled_converter_files() {")
    out.append(f"    static const std::array<BundledScript, {len(names)}> files{{{{")
    for relative in names:
        out.append(f'        {{.name = "convert/{relative}", .text = convert_{identifier(relative)}()}},')
    out.append("    }};")
    out.append("    return files;")
    out.append("}")
    out.append("")
    out.append("// clang-format on")
    out.append("")
    out.append("}  // namespace apogee::harness")
    return "\n".join(out) + "\n"


def main() -> int:
    OUT_TRAINING.write_text(generate_training(), encoding="utf-8")
    OUT_CONVERTER.write_text(generate_converter(), encoding="utf-8")
    print(f"wrote {OUT_TRAINING.relative_to(ROOT)} and {OUT_CONVERTER.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
