#!/usr/bin/env python3
"""Regenerate the compiled-in graph assets: the HTML export's page.

    python3 scripts/generate_graph_assets.py        # run from anywhere

Reads the shipped file and rewrites the one generated translation unit:

    assets/graph/graph.html  ->  source/business/graph/html_template.cpp

The FILE is the source of truth: edit it, run this, and commit both.
tests/business/graph/export_test.cpp fails the build the moment the literal and
its file differ -- the contract the clerks' prompts keep.

The page is emitted as a list of raw-string chunks under 15 000 bytes, split on
line boundaries and joined at first use: MSVC refuses a single string literal
over 16 380 bytes and a concatenation over 65 535 (the same rule
generate_training_assets.py follows).
"""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "assets" / "graph" / "graph.html"
OUT = ROOT / "source" / "business" / "graph" / "html_template.cpp"

CHUNK_BYTES = 15_000
DELIMITER = "HTML"


def chunks_of(text: str) -> list[str]:
    """Splits on line boundaries so every chunk stays under the limit."""
    pieces: list[str] = []
    current = ""
    for line in text.splitlines(keepends=True):
        if len((current + line).encode("utf-8")) > CHUNK_BYTES and current:
            pieces.append(current)
            current = ""
        current += line
    if current or not pieces:
        pieces.append(current)
    return pieces


def generate() -> str:
    text = PAGE.read_text(encoding="utf-8")
    if f"){DELIMITER}\"" in text:
        raise SystemExit(f"{PAGE}: the page contains the raw-string terminator ){DELIMITER}\"")
    pieces = chunks_of(text)
    out = [
        '#include "graph/html_template.h"',
        "",
        "#include <array>",
        "#include <string>",
        "#include <string_view>",
        "",
        "// GENERATED by scripts/generate_graph_assets.py from",
        "// lib/src/cli/assets/graph/graph.html -- the page `apogee graph export html`",
        "// fills. The shipped file and these literals are byte-identical, and",
        "// tests/business/graph/export_test.cpp fails the build the moment they",
        "// drift. Edit the FILE, then regenerate; never edit a literal here.",
        "",
        "namespace apogee::graph {",
        "// clang-format off",
        "namespace {",
        "",
        f"constexpr std::array<std::string_view, {len(pieces)}> kGraphPage{{{{",
    ]
    for piece in pieces:
        out.append(f'    R"{DELIMITER}({piece}){DELIMITER}",')
    out += [
        "}};",
        "",
        "}  // namespace",
        "",
        "const std::string& html_template() {",
        "    static const std::string text = [] {",
        "        std::string joined;",
        "        for (const std::string_view chunk : kGraphPage) {",
        "            joined.append(chunk);",
        "        }",
        "        return joined;",
        "    }();",
        "    return text;",
        "}",
        "",
        "// clang-format on",
        "}  // namespace apogee::graph",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    generated = generate()
    if OUT.exists() and OUT.read_text(encoding="utf-8") == generated:
        print(f"{OUT.relative_to(ROOT)}: unchanged")
        return 0
    OUT.write_text(generated, encoding="utf-8")
    print(f"{OUT.relative_to(ROOT)}: written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
